spring:
  datasource:
    url: jdbc:mysql://adcpersist_dev.mysql.dbaas.com.br:3306/adcpersist_dev
    username: adcpersist_dev
    password: labsprog
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8081
management.endpoints.web.exposure.include: '*'